version: 0.0
os: linux
files:
  - source: ./
    destination:  /var/www/projects/nomad_cafe_rails_app_v2
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: rfujii
  AfterInstall:
    - location: scripts/bundle_install.sh
      timeout: 300
      runas: rfujii
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: rfujii