version: 2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.3.3-node-browsers
        environment: 
          BUNDLE_PATH: vendor/bundle
          RAILS_ENV: test
          MYSQL_HOST: 127.0.0.1
          MYSQL_USERNAME: 'root'
          MYSQL_PASSWORD: ''
          MYSQL_PORT: 3306
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          # MYSQL_ROOT_PASSWORD: ''
          # MYSQL_DATABASE: wdb-circleci-rails_test
          MYSQL_DATABASE: nomad_cafe_rails_app_v2_test
          MYSQL_ROOT_HOST: '%'
      - image: node:6.10.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Bundle Install
          command: bundle check || bundle install --path vendor/bundle
      # - run:
      #     name: install yarn
      #     command: npm install yarn
      # - run:
      #     name: Yarn Install
      #     command: bundle exec yarn install
      - save_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: データベースの起動待機
          command: |
            dockerize -wait \
            tcp://127.0.0.1:3306 -timeout 120s
      - run: rm ./config/database.yml
      - run: mv ./config/database.yml.ci ./config/database.yml
      - run:
          name: データベースセットアップ（DB作成）
          command: bin/rails db:create
      - run:
          name: データベースセットアップ（テーブル作成）
          command: bin/rails db:migrate
      # - run:
      #     name: webpackビルド
      #     command: bundle exec bin/webpack
      # - run:
      #     name: コンパイル
      #     command: bundle exec rails webpacker:compile NODE_ENV=test 
      - run:
          name: Rspecの実行
          command: bin/rspec spec/models/ || bin/rspec spec/requests/


workflows:
  version: 2
  build_and_test:
      jobs:
        - build
