version: 2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.3.3-node-browsers
        environment: 
          BUNDLE_PATH: vendor/bundle
          RAILS_ENV: test
          MYSQL_HOST: 127.0.0.1
          MYSQL_USERNAME: 'root'
          MYSQL_PASSWORD: ''
          MYSQL_PORT: 3306
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          # MYSQL_ROOT_PASSWORD: ''
          # MYSQL_DATABASE: wdb-circleci-rails_test
          MYSQL_DATABASE: nomad_cafe_rails_app_v2_test
          MYSQL_ROOT_HOST: '%'
      # - image: node:6.10.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys: 
            - v1-bundle-{{ checksum "Gemfile.lock" }}
            - v1-bundle-
      # - restore_cache:
      #     key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Bundle Install
          command: bundle check || bundle install --path vendor/bundle
      # - run:
      #     name: install yarn
      #     command: npm install yarn
      # - run:
      #     name: Yarn Install
      #     command: bundle exec yarn install
      - save_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      # - save_cache:
      #     key: v1-dependencies-{{ checksum "package.json" }}
      #     paths:
      #       - node_modules
      - run:
          name: データベースの起動待機
          command: |
            dockerize -wait \
            tcp://127.0.0.1:3306 -timeout 120s
      - run: rm ./config/database.yml
      - run: mv ./config/database.yml.ci ./config/database.yml
      - run:
          name: データベースセットアップ（DB作成）
          command: bin/rails db:create
      - run:
          name: データベースセットアップ（テーブル作成）
          command: bin/rails db:migrate
      # - run:
      #     name: webpackビルド
      #     command: bundle exec bin/webpack
      # - run:
      #     name: コンパイル
      #     command: bundle exec rails webpacker:compile NODE_ENV=test 
      - run:
          name: Rspecの実行
          command: bin/rspec spec/models/ || bin/rspec spec/requests/
  deploy:
    docker:
      - image: cdssnc/aws-cli
        environment:
          DEPLOY_APPLICATION: nomad-v2-codedeploy
          DEPLOY_GROUP: nomad-v2-codedeploy-group
          DEPLOY_REPOSITORY: ryofu1210/nomad_cafe_rails_app_v2
    steps:
      - run:
          name: "Set AWS region"
          command: aws configure set region ap-northeast-1
      - run:
          name: "Run AWS CodeDeploy"
          command: |
            aws deploy create-deployment \
            --application-name ${DEPLOY_APPLICATION} \
            --deployment-group-name ${DEPLOY_GROUP} \
            --github-location repository="${DEPLOY_REPOSITORY}",commitId="${CIRCLE_SHA1}"

workflows:
  version: 2
  build_and_test:
      jobs:
        - build
        - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
